### ISSUE TITLE
Failed Registration Bug

### ISSUE THREAD

**Issue by WahomeKezia** [WahomeKezia/Student-Management-Plaform_MERN#1]
this is an bug that I'm facing . Frontend runs well and the server side is showing no errors 
but the register or login button are not sending the authentication data  
After inspecting the browser this is the  error message on the console 

```
AxiosErrorcode: "ERR_BAD_REQUEST"config: {transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}message: "Request failed with status code 404"name: "AxiosError"request: XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}response: {data: '<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta char…t POST /undefined/AdminReg</pre>\n</body>\n</html>\n', status: 404, statusText: 'Not Found', headers: AxiosHeaders, config: {…}, …}stack: "AxiosError: Request failed with status code 404\n    at settle (http://localhost:3000/static/js/bundle.js:151850:12)\n    at XMLHttpRequest.onloadend (http://localhost:3000/static/js/bundle.js:150541:66)"[[Prototype]]: Error
Adminregister:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
 ```

**Axios Error**

I tried resolving it by adding this to store.js  
```middleware: getDefaultMiddleware =>
    getDefaultMiddleware({
      serializableCheck: false,
    }),```

the bug is still persistent

**Comment by WahomeKezia** [comment]
I am rechecking all my routes and middleware

**Comment by WahomeKezia** [comment]
I fixed the routes to solve this error
